SELECT
  CAST(a AS NVARCHAR(20)) AS [a1],
  CAST(b AS VARCHAR(10)) AS [b1],
  CAST(c AS CHAR(4)) AS [c1],
  CAST(d AS TINYTEXT) AS [d1],
  CAST(e AS MEDIUMTEXT) AS [e1],
  CAST(f AS LONGTEXT) AS [f1],
  CAST(g AS CLOB(400)) AS [g1],
  CAST(h AS DOUBLE PRECISION) AS [h1],
  CAST(i AS DOUBLE) AS [i1],
  CAST(j AS FLOAT) AS [j1],
  CAST(k AS REAL) AS [k1],
  CAST(l AS NUMERIC) AS [l1],
  CAST(m AS DECIMAL(6, 2)) AS [m1],
  CAST(n AS BOOLEAN) AS [n1],
  CAST(o AS DATE) AS [o1],
  CAST(p AS DATETIME) AS [p1],
  CAST(q AS TIMESTAMP) AS [q1],
  CAST(r AS TIME) AS [r1],
  CAST(s AS INT) AS [s1],
  CAST(t AS INTEGER) AS [t1],
  CAST(u AS INT4) AS [u1],
  CAST(v AS BIGINT) AS [v1],
  CAST(w AS MEDIUMINT) AS [w1],
  CAST(x AS SMALLINT) AS [x1],
  CAST(y AS TINYINT) AS [y1],
  CAST(z AS BLOB) AS [z1]
FROM
  "ALL_DATATYPES";

CREATE TABLE "MORE_DATATYPES" (
  a VARCHAR(20) NOT NULL,
  b TEXT NULL,
  c INT8 NOT NULL,
  d DOUBLE NULL,
  e BLOB NULL
);
