-- original: analyze7.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

CREATE TABLE t1(a,b,c,d);
    CREATE INDEX t1a ON t1(a);
    CREATE INDEX t1b ON t1(b);
    CREATE INDEX t1cd ON t1(c,d);
    CREATE VIRTUAL TABLE nums USING wholenumber;
    INSERT INTO t1 SELECT value, value, value/100, value FROM nums
                    WHERE value BETWEEN 1 AND 256;
    EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE b=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=2
;ANALYZE t1a
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE b=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=2
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123 AND b=123
;ANALYZE t1cd
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE b=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=?
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=2
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=2
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123 AND b=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=123 AND b=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123 AND c=123
;EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=123 AND d=123 AND b=123;