-- original: boundary2.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

SELECT a FROM t1 WHERE r > -1 ORDER BY a
;SELECT a FROM t1 WHERE r > -1 ORDER BY a DESC
;SELECT a FROM t1 WHERE r > -1 ORDER BY r
;SELECT a FROM t1 WHERE r > -1 ORDER BY r DESC
;SELECT a FROM t1 WHERE r > -1 ORDER BY x
;SELECT a FROM t1 WHERE r >= -1 ORDER BY a
;SELECT a FROM t1 WHERE r >= -1 ORDER BY a DESC
;SELECT a FROM t1 WHERE r >= -1 ORDER BY r
;SELECT a FROM t1 WHERE r >= -1 ORDER BY r DESC
;SELECT a FROM t1 WHERE r >= -1 ORDER BY x
;SELECT a FROM t1 WHERE r < -1 ORDER BY a
;SELECT a FROM t1 WHERE r < -1 ORDER BY a DESC
;SELECT a FROM t1 WHERE r < -1 ORDER BY r
;SELECT a FROM t1 WHERE r < -1 ORDER BY r DESC
;SELECT a FROM t1 WHERE r < -1 ORDER BY x
;SELECT a FROM t1 WHERE r <= -1 ORDER BY a
;SELECT a FROM t1 WHERE r <= -1 ORDER BY a DESC
;SELECT a FROM t1 WHERE r <= -1 ORDER BY r
;SELECT a FROM t1 WHERE r <= -1 ORDER BY r DESC
;SELECT a FROM t1 WHERE r <= -1 ORDER BY x
;SELECT * FROM t1 WHERE r=-2
;SELECT r, a FROM t1 WHERE x='fffffffffffffffe'
;SELECT r, x FROM t1 WHERE a=33
;SELECT a FROM t1 WHERE r > -2 ORDER BY a
;SELECT a FROM t1 WHERE r > -2 ORDER BY a DESC
;SELECT a FROM t1 WHERE r > -2 ORDER BY r
;SELECT a FROM t1 WHERE r > -2 ORDER BY r DESC
;SELECT a FROM t1 WHERE r > -2 ORDER BY x
;SELECT a FROM t1 WHERE r >= -2 ORDER BY a
;SELECT a FROM t1 WHERE r >= -2 ORDER BY a DESC
;SELECT a FROM t1 WHERE r >= -2 ORDER BY r
;SELECT a FROM t1 WHERE r >= -2 ORDER BY r DESC
;SELECT a FROM t1 WHERE r >= -2 ORDER BY x
;SELECT a FROM t1 WHERE r < -2 ORDER BY a
;SELECT a FROM t1 WHERE r < -2 ORDER BY a DESC
;SELECT a FROM t1 WHERE r < -2 ORDER BY r
;SELECT a FROM t1 WHERE r < -2 ORDER BY r DESC
;SELECT a FROM t1 WHERE r < -2 ORDER BY x
;SELECT a FROM t1 WHERE r <= -2 ORDER BY a
;SELECT a FROM t1 WHERE r <= -2 ORDER BY a DESC
;SELECT a FROM t1 WHERE r <= -2 ORDER BY r
;SELECT a FROM t1 WHERE r <= -2 ORDER BY r DESC
;SELECT a FROM t1 WHERE r <= -2 ORDER BY x
;SELECT * FROM t1 WHERE r=2097152
;SELECT r, a FROM t1 WHERE x='0000000000200000'
;SELECT r, x FROM t1 WHERE a=42
;SELECT a FROM t1 WHERE r > 2097152 ORDER BY a
;SELECT a FROM t1 WHERE r > 2097152 ORDER BY a DESC
;SELECT a FROM t1 WHERE r > 2097152 ORDER BY r
;SELECT a FROM t1 WHERE r > 2097152 ORDER BY r DESC
;SELECT a FROM t1 WHERE r > 2097152 ORDER BY x
;SELECT a FROM t1 WHERE r >= 2097152 ORDER BY a
;SELECT a FROM t1 WHERE r >= 2097152 ORDER BY a DESC
;SELECT a FROM t1 WHERE r >= 2097152 ORDER BY r
;SELECT a FROM t1 WHERE r >= 2097152 ORDER BY r DESC
;SELECT a FROM t1 WHERE r >= 2097152 ORDER BY x
;SELECT a FROM t1 WHERE r < 2097152 ORDER BY a
;SELECT a FROM t1 WHERE r < 2097152 ORDER BY a DESC
;SELECT a FROM t1 WHERE r < 2097152 ORDER BY r
;SELECT a FROM t1 WHERE r < 2097152 ORDER BY r DESC
;SELECT a FROM t1 WHERE r < 2097152 ORDER BY x
;SELECT a FROM t1 WHERE r <= 2097152 ORDER BY a
;SELECT a FROM t1 WHERE r <= 2097152 ORDER BY a DESC
;SELECT a FROM t1 WHERE r <= 2097152 ORDER BY r
;SELECT a FROM t1 WHERE r <= 2097152 ORDER BY r DESC
;SELECT a FROM t1 WHERE r <= 2097152 ORDER BY x
;SELECT * FROM t1 WHERE r=128
;SELECT r, a FROM t1 WHERE x='0000000000000080'
;SELECT r, x FROM t1 WHERE a=49
;SELECT a FROM t1 WHERE r > 128 ORDER BY a
;SELECT a FROM t1 WHERE r > 128 ORDER BY a DESC
;SELECT a FROM t1 WHERE r > 128 ORDER BY r
;SELECT a FROM t1 WHERE r > 128 ORDER BY r DESC
;SELECT a FROM t1 WHERE r > 128 ORDER BY x
;SELECT a FROM t1 WHERE r >= 128 ORDER BY a
;SELECT a FROM t1 WHERE r >= 128 ORDER BY a DESC
;SELECT a FROM t1 WHERE r >= 128 ORDER BY r
;SELECT a FROM t1 WHERE r >= 128 ORDER BY r DESC
;SELECT a FROM t1 WHERE r >= 128 ORDER BY x
;SELECT a FROM t1 WHERE r < 128 ORDER BY a
;SELECT a FROM t1 WHERE r < 128 ORDER BY a DESC
;SELECT a FROM t1 WHERE r < 128 ORDER BY r
;SELECT a FROM t1 WHERE r < 128 ORDER BY r DESC
;SELECT a FROM t1 WHERE r < 128 ORDER BY x
;SELECT a FROM t1 WHERE r <= 128 ORDER BY a
;SELECT a FROM t1 WHERE r <= 128 ORDER BY a DESC
;SELECT a FROM t1 WHERE r <= 128 ORDER BY r
;SELECT a FROM t1 WHERE r <= 128 ORDER BY r DESC
;SELECT a FROM t1 WHERE r <= 128 ORDER BY x
;SELECT * FROM t1 WHERE r=255
;SELECT r, a FROM t1 WHERE x='00000000000000ff'
;SELECT r, x FROM t1 WHERE a=30
;SELECT a FROM t1 WHERE r > 255 ORDER BY a
;SELECT a FROM t1 WHERE r > 255 ORDER BY a DESC
;SELECT a FROM t1 WHERE r > 255 ORDER BY r
;SELECT a FROM t1 WHERE r > 255 ORDER BY r DESC
;SELECT a FROM t1 WHERE r > 255 ORDER BY x
;SELECT a FROM t1 WHERE r >= 255 ORDER BY a
;SELECT a FROM t1 WHERE r >= 255 ORDER BY a DESC
;SELECT a FROM t1 WHERE r >= 255 ORDER BY r;