-- original: boundary1.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

SELECT a FROM t1 WHERE rowid > -1 ORDER BY a
;SELECT a FROM t1 WHERE rowid > -1 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid > -1 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid > -1 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid > -1 ORDER BY x
;SELECT a FROM t1 WHERE rowid >= -1 ORDER BY a
;SELECT a FROM t1 WHERE rowid >= -1 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid >= -1 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid >= -1 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid >= -1 ORDER BY x
;SELECT a FROM t1 WHERE rowid < -1 ORDER BY a
;SELECT a FROM t1 WHERE rowid < -1 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid < -1 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid < -1 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid < -1 ORDER BY x
;SELECT a FROM t1 WHERE rowid <= -1 ORDER BY a
;SELECT a FROM t1 WHERE rowid <= -1 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid <= -1 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid <= -1 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid <= -1 ORDER BY x
;SELECT * FROM t1 WHERE rowid=-2
;SELECT rowid, a FROM t1 WHERE x='fffffffffffffffe'
;SELECT rowid, x FROM t1 WHERE a=33
;SELECT a FROM t1 WHERE rowid > -2 ORDER BY a
;SELECT a FROM t1 WHERE rowid > -2 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid > -2 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid > -2 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid > -2 ORDER BY x
;SELECT a FROM t1 WHERE rowid >= -2 ORDER BY a
;SELECT a FROM t1 WHERE rowid >= -2 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid >= -2 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid >= -2 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid >= -2 ORDER BY x
;SELECT a FROM t1 WHERE rowid < -2 ORDER BY a
;SELECT a FROM t1 WHERE rowid < -2 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid < -2 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid < -2 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid < -2 ORDER BY x
;SELECT a FROM t1 WHERE rowid <= -2 ORDER BY a
;SELECT a FROM t1 WHERE rowid <= -2 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid <= -2 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid <= -2 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid <= -2 ORDER BY x
;SELECT * FROM t1 WHERE rowid=2097152
;SELECT rowid, a FROM t1 WHERE x='0000000000200000'
;SELECT rowid, x FROM t1 WHERE a=42
;SELECT a FROM t1 WHERE rowid > 2097152 ORDER BY a
;SELECT a FROM t1 WHERE rowid > 2097152 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid > 2097152 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid > 2097152 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid > 2097152 ORDER BY x
;SELECT a FROM t1 WHERE rowid >= 2097152 ORDER BY a
;SELECT a FROM t1 WHERE rowid >= 2097152 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid >= 2097152 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid >= 2097152 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid >= 2097152 ORDER BY x
;SELECT a FROM t1 WHERE rowid < 2097152 ORDER BY a
;SELECT a FROM t1 WHERE rowid < 2097152 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid < 2097152 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid < 2097152 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid < 2097152 ORDER BY x
;SELECT a FROM t1 WHERE rowid <= 2097152 ORDER BY a
;SELECT a FROM t1 WHERE rowid <= 2097152 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid <= 2097152 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid <= 2097152 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid <= 2097152 ORDER BY x
;SELECT * FROM t1 WHERE rowid=128
;SELECT rowid, a FROM t1 WHERE x='0000000000000080'
;SELECT rowid, x FROM t1 WHERE a=49
;SELECT a FROM t1 WHERE rowid > 128 ORDER BY a
;SELECT a FROM t1 WHERE rowid > 128 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid > 128 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid > 128 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid > 128 ORDER BY x
;SELECT a FROM t1 WHERE rowid >= 128 ORDER BY a
;SELECT a FROM t1 WHERE rowid >= 128 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid >= 128 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid >= 128 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid >= 128 ORDER BY x
;SELECT a FROM t1 WHERE rowid < 128 ORDER BY a
;SELECT a FROM t1 WHERE rowid < 128 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid < 128 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid < 128 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid < 128 ORDER BY x
;SELECT a FROM t1 WHERE rowid <= 128 ORDER BY a
;SELECT a FROM t1 WHERE rowid <= 128 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid <= 128 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid <= 128 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid <= 128 ORDER BY x
;SELECT * FROM t1 WHERE rowid=255
;SELECT rowid, a FROM t1 WHERE x='00000000000000ff'
;SELECT rowid, x FROM t1 WHERE a=30
;SELECT a FROM t1 WHERE rowid > 255 ORDER BY a
;SELECT a FROM t1 WHERE rowid > 255 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid > 255 ORDER BY rowid
;SELECT a FROM t1 WHERE rowid > 255 ORDER BY rowid DESC
;SELECT a FROM t1 WHERE rowid > 255 ORDER BY x
;SELECT a FROM t1 WHERE rowid >= 255 ORDER BY a
;SELECT a FROM t1 WHERE rowid >= 255 ORDER BY a DESC
;SELECT a FROM t1 WHERE rowid >= 255 ORDER BY rowid;