-- original: delete.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

CREATE TABLE table1(f1 int, f2 int)
;INSERT INTO table1 VALUES(1,2)
;INSERT INTO table1 VALUES(2,4)
;INSERT INTO table1 VALUES(3,8)
;INSERT INTO table1 VALUES(4,16)
;SELECT * FROM table1 ORDER BY f1
;DELETE FROM table1 WHERE f1=3
;SELECT * FROM table1 ORDER BY f1
;CREATE INDEX index1 ON table1(f1)
;PRAGMA count_changes=on
;EXPLAIN DELETE FROM table1 WHERE f1=3
;DELETE FROM 'table1' WHERE f1=3
;SELECT * FROM table1 ORDER BY f1
;DELETE FROM table1 WHERE f1=2
;SELECT * FROM table1 ORDER BY f1
;CREATE TABLE table2(f1 int, f2 int)
;DELETE FROM table1
;SELECT count(*) FROM table1
;BEGIN TRANSACTION
;COMMIT
;SELECT count(*) FROM table1
;DELETE FROM table1
;BEGIN TRANSACTION
;COMMIT
;SELECT count(*) FROM table1
;PRAGMA count_changes=off
;DELETE FROM table1
;SELECT count(*) FROM table1
;BEGIN TRANSACTION
;COMMIT
;SELECT count(*) FROM table1
;DELETE FROM table1 WHERE f1==sub_i
;SELECT count(*) FROM table1
;DELETE FROM table1 WHERE f1>50
;SELECT count(*) FROM table1
;DELETE FROM table1 WHERE f1==sub_i
;SELECT f1 FROM table1 ORDER BY f1
;DELETE FROM table1 WHERE f1==sub_i
;SELECT f1 FROM table1 ORDER BY f1
;DELETE FROM table1 WHERE f1!=48
;SELECT f1 FROM table1 ORDER BY f1
;BEGIN; DELETE FROM table1
;DELETE FROM table2
;COMMIT
;SELECT count(*) FROM table1
;SELECT count(*) FROM table2
;SELECT f1 FROM table1 WHERE f1<10 ORDER BY f1
;SELECT f1 FROM table2 WHERE f1<10 ORDER BY f1
;DELETE FROM table1 WHERE f1>7
;SELECT f1 FROM table1 ORDER BY f1
;DELETE FROM table2 WHERE f1>7
;SELECT f1 FROM table2 ORDER BY f1
;DELETE FROM table1
;SELECT f1 FROM table1
;INSERT INTO table1 VALUES(2,3)
;SELECT f1 FROM table1
;DELETE FROM table2
;SELECT f1 FROM table2
;INSERT INTO table2 VALUES(2,3)
;SELECT f1 FROM table2
;CREATE TABLE t3(a);
    INSERT INTO t3 VALUES(1);
    INSERT INTO t3 SELECT a+1 FROM t3;
    INSERT INTO t3 SELECT a+2 FROM t3;
    SELECT * FROM t3
;CREATE TABLE cnt(del);
      INSERT INTO cnt VALUES(0);
      CREATE TRIGGER r1 AFTER DELETE ON t3 FOR EACH ROW BEGIN
        UPDATE cnt SET del=del+1;
      END;
      DELETE FROM t3 WHERE a<2;
      SELECT * FROM t3
;SELECT * FROM cnt
;DELETE FROM t3;
      SELECT * FROM t3
;SELECT * FROM cnt
;INSERT INTO t3 VALUES(1);
      INSERT INTO t3 SELECT a+1 FROM t3;
      INSERT INTO t3 SELECT a+2 FROM t3;
      CREATE TABLE t4 AS SELECT * FROM t3;
      PRAGMA count_changes=ON;
      DELETE FROM t3;
      DELETE FROM t4
;DELETE FROM t3
;PRAGMA count_changes=OFF;
    INSERT INTO t3 VALUES(123);
    SELECT * FROM t3
;SELECT * FROM t3
;SELECT * FROM t3
;SELECT * FROM t3
;CREATE TABLE t5(a, b);
    CREATE TABLE t6(c, d);
    INSERT INTO t5 VALUES(1, 2);
    INSERT INTO t5 VALUES(3, 4);
    INSERT INTO t5 VALUES(5, 6);
    INSERT INTO t6 VALUES('a', 'b');
    INSERT INTO t6 VALUES('c', 'd');
    CREATE INDEX i5 ON t5(a);
    CREATE INDEX i6 ON t6(c)
;SELECT t5.rowid AS r, c, d FROM t5, t6 ORDER BY a
;DELETE FROM t5
;INSERT INTO t5 VALUES(1, 2);
    INSERT INTO t5 VALUES(3, 4);
    INSERT INTO t5 VALUES(5, 6)
;SELECT t5.rowid AS r, c, d FROM t5, t6 ORDER BY a
;DELETE FROM t5 WHERE rowid = 2
;DELETE FROM t5;
    INSERT INTO t5 VALUES(1, 2);
    INSERT INTO t5 VALUES(3, 4);
    INSERT INTO t5 VALUES(5, 6)
;SELECT t5.rowid AS r, c, d FROM t5, t6 ORDER BY a
;DELETE FROM t5 WHERE rowid = 1
;DELETE FROM t5;
    INSERT INTO t5 VALUES(1, 2);
    INSERT INTO t5 VALUES(3, 4);
    INSERT INTO t5 VALUES(5, 6)
;SELECT t5.rowid AS r, c, d FROM t5, t6 ORDER BY a
;DELETE FROM t5 WHERE rowid = 3;