-- original: expr.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

SELECT t1=NULL, t2='hi'
;SELECT t1=NULL, t2='hi'
;SELECT t1=NULL, t2='hi'
;SELECT t1='xyz', t2='abc'
;SELECT t1=NULL, t2='abc'
;SELECT t1='xyz', t2=NULL
;SELECT t1='xyz', t2='abc'
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2='Abc'
;SELECT t1='abc', t2='Abc'
;SELECT t1='abc', t2='Bbc'
;SELECT t1='abc', t2='Bbc'
;SELECT t1='0', t2='0.0'
;SELECT t1='0.000', t2='0.0'
;SELECT t1=' 0.000', t2=' 0.0'
;SELECT t1='0.0', t2='abc'
;SELECT t1='0.0', t2='abc'
;SELECT r1='0.0', r2='abc'
;SELECT r1='abc', r2='Abc'
;SELECT r1='abc', r2='Abc'
;SELECT r1='abc', r2='Bbc'
;SELECT r1='abc', r2='Bbc'
;SELECT r1='0', r2='0.0'
;SELECT r1='0.000', r2='0.0'
;SELECT r1=' 0.000', r2=' 0.0'
;SELECT r1='0.0', r2='abc'
;SELECT r1='0.0', r2='abc'
;SELECT r1='0.0', r2='abc'
;SELECT t1='abc', t2='xyz'
;SELECT t1='abc', t2='abc'
;SELECT t1='abc', t2='ABC'
;SELECT t1='abc', t2='a_c'
;SELECT t1='abc', t2='A_C'
;SELECT t1='abc', t2='abc_'
;SELECT t1='abc', t2='a%c'
;SELECT t1='abc', t2='A%C'
;SELECT t1='abdc', t2='a%c'
;SELECT t1='ac', t2='a%c'
;SELECT t1='ac', t2='A%C'
;SELECT t1='abxyzzyc', t2='a%c'
;SELECT t1='abxyzzyc', t2='A%C'
;SELECT t1='abxyzzy', t2='a%c'
;SELECT t1='abxyzzy', t2='A%C'
;SELECT t1='abxyzzycx', t2='a%c'
;SELECT t1='abxyzzycy', t2='a%cx'
;SELECT t1='abxyzzycx', t2='A%C'
;SELECT t1='abxyzzycy', t2='A%CX'
;SELECT t1='abc', t2='a%_c'
;SELECT t1='ac', t2='a%_c'
;SELECT t1='abc', t2='A%_C'
;SELECT t1='ac', t2='A%_C'
;SELECT t1='abxyzzyc', t2='a%_c'
;SELECT t1='abxyzzyc', t2='A%_C'
;SELECT t1='abc', t2='xyz'
;SELECT t1='abc', t2='abc'
;SELECT t1='abc', t2='ABC'
;SELECT t1='A'
;SELECT t1='AB'
;SELECT t1='au0080c', t2='a_c'
;SELECT t1='au0080c', t2='A_C'
;SELECT t1='au07FFc', t2='a_c'
;SELECT t1='au07FFc', t2='A_C'
;SELECT t1='au0800c', t2='a_c'
;SELECT t1='au0800c', t2='A_C'
;SELECT t1='auFFFFc', t2='a_c'
;SELECT t1='auFFFFc', t2='A_C'
;SELECT t1='au0080', t2='A__'
;SELECT t1='au07FF', t2='A__'
;SELECT t1='au0800', t2='A__'
;SELECT t1='auFFFF', t2='A__'
;SELECT t1='axuABCD', t2='a_uABCD'
;SELECT t1='axuABCD', t2='A_uABCD'
;SELECT t1='axu1234', t2='a%u1234'
;SELECT t1='axu1234', t2='A%u1234'
;SELECT t1='axuFEDC', t2='a_%'
;SELECT t1='axuFEDC', t2='A_%'
;SELECT t1='axuFEDCyuFEDC', t2='a%uFEDC'
;SELECT t1='axuFEDCyuFEDC', t2='A%uFEDC'
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2=NULL
;SELECT t1='abc', t2='a_c'
;SELECT t1='abc', t2='A_C'
;SELECT t1='a_c', t2='a7_c'
;SELECT t1='a_c', t2='A7_C'
;SELECT t1='abc', t2='a7_c'
;SELECT t1='abc', t2='A7_C'
;SELECT t1='a7Xc', t2='a7_c';