-- original: lock3.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

CREATE TABLE t1(a);
    INSERT INTO t1 VALUES(1)
;SELECT * FROM t1
;BEGIN DEFERRED TRANSACTION
;INSERT INTO t1 VALUES(2)
;END TRANSACTION
;SELECT * FROM t1
;BEGIN IMMEDIATE TRANSACTION
;END TRANSACTION
;BEGIN EXCLUSIVE TRANSACTION
;END TRANSACTION;