-- original: temptable.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

CREATE TABLE t1(a,b,c)
;INSERT INTO t1 VALUES(1,2,3)
;SELECT * FROM t1
;SELECT * FROM sqlite_master
;SELECT * FROM t1
;SELECT name FROM sqlite_master
;SELECT name FROM sqlite_master
;CREATE TEMP TABLE t2(x,y,z);
    INSERT INTO t2 VALUES(4,5,6)
;SELECT * FROM t2
;SELECT * FROM sqlite_master
;INSERT INTO t2 VALUES(8,9,0)
;SELECT * FROM t2 ORDER BY x
;DELETE FROM t2 WHERE x==8
;SELECT * FROM t2 ORDER BY x
;DELETE FROM t2
;SELECT * FROM t2
;INSERT INTO t2 VALUES(7,6,5);
     INSERT INTO t2 VALUES(4,3,2);
     SELECT * FROM t2 ORDER BY x
;DROP TABLE t2
;BEGIN TRANSACTION;
    CREATE TEMPORARY TABLE t2(x,y);
    INSERT INTO t2 VALUES(1,2);
    SELECT * FROM t2
;ROLLBACK
;BEGIN TRANSACTION;
    CREATE TEMPORARY TABLE t2(x,y);
    INSERT INTO t2 VALUES(1,2);
    SELECT * FROM t2
;COMMIT
;CREATE INDEX i2 ON t2(x);
    SELECT name FROM sqlite_master WHERE type='index'
;SELECT y FROM t2 WHERE x=1
;DROP INDEX i2;
    SELECT y FROM t2 WHERE x=1
;CREATE INDEX i2 ON t2(x);
    DROP TABLE t2
;CREATE TEMP TABLE t2(x,y);
    INSERT INTO t2 VALUES(10,20);
    SELECT * FROM t2
;CREATE TABLE t2(x,y,z);
    INSERT INTO t2 VALUES(9,8,7);
    SELECT * FROM t2
;CREATE TEMP TABLE t2(x unique,y);
    INSERT INTO t2 VALUES(1,2);
    SELECT * FROM t2
;CREATE TABLE t2(x unique, y);
    INSERT INTO t2 VALUES(3,4);
    SELECT * FROM t2
;SELECT * FROM t2
;SELECT * FROM t2
;SELECT * FROM t2
;SELECT * FROM t2
;CREATE TEMP TABLE mask(a,b,c)
;CREATE INDEX mask ON t2(x);
    SELECT * FROM t2
;SELECT y FROM t2 WHERE x=3
;SELECT y FROM t2 WHERE x=3
;INSERT INTO t2 VALUES(1,2);
    SELECT y FROM t2 WHERE x=1
;SELECT y FROM t2 WHERE x=3
;SELECT y FROM t2 WHERE x=1
;SELECT y FROM t2 WHERE x=3
;CREATE TABLE t8(x);
    INSERT INTO t8 VALUES('xyzzy');
    SELECT * FROM t8
;SELECT * FROM t8
;CREATE TEMP TABLE tbl2(a, b)
;CREATE TABLE tbl(a, b);
    INSERT INTO tbl VALUES(1, 2)
;SELECT * FROM tbl
;CREATE TEMP TABLE tbl(a, b)
;SELECT * FROM tbl;