-- original: tkt-385a5b56b9.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

CREATE TABLE t1(x, y);
  INSERT INTO t1 VALUES(1, NULL);
  INSERT INTO t1 VALUES(2, NULL);
  INSERT INTO t1 VALUES(1, NULL)
;SELECT DISTINCT x, y FROM t1
;CREATE UNIQUE INDEX i1 ON t1(x, y)
;SELECT DISTINCT x, y FROM t1
;CREATE TABLE t2(x, y NOT NULL);
  CREATE UNIQUE INDEX t2x ON t2(x);
  CREATE UNIQUE INDEX t2y ON t2(y)
;SELECT DISTINCT x FROM t2
;SELECT DISTINCT y FROM t2
;SELECT DISTINCT x, y FROM t2 WHERE y=10
;SELECT DISTINCT x, y FROM t2 WHERE x=10;