-- original: tkt-9a8b09f8e6.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

CREATE TABLE t1(x TEXT);
    INSERT INTO t1 VALUES('1')
;CREATE TABLE t2(x INTEGER);
    INSERT INTO t2 VALUES(1)
;CREATE TABLE t3(x REAL);
    INSERT INTO t3 VALUES(1.0)
;CREATE TABLE t4(x REAL);
    INSERT INTO t4 VALUES(1.11)
;CREATE TABLE t5(x, y);
    INSERT INTO t5 VALUES('1', 'one');
    INSERT INTO t5 VALUES(1, 'two');
    INSERT INTO t5 VALUES('1.0', 'three');
    INSERT INTO t5 VALUES(1.0, 'four')
;SELECT x FROM t1 WHERE x IN (1)
;SELECT x FROM t1 WHERE x IN (1.0)
;SELECT x FROM t1 WHERE x IN ('1')
;SELECT x FROM t1 WHERE x IN ('1.0')
;SELECT x FROM t1 WHERE 1 IN (x)
;SELECT x FROM t1 WHERE 1.0 IN (x)
;SELECT x FROM t1 WHERE '1' IN (x)
;SELECT x FROM t1 WHERE '1.0' IN (x)
;SELECT x FROM t2 WHERE x IN (1)
;SELECT x FROM t2 WHERE x IN (1.0)
;SELECT x FROM t2 WHERE x IN ('1')
;SELECT x FROM t2 WHERE x IN ('1.0')
;SELECT x FROM t2 WHERE 1 IN (x)
;SELECT x FROM t2 WHERE 1.0 IN (x)
;SELECT x FROM t2 WHERE '1' IN (x)
;SELECT x FROM t2 WHERE '1.0' IN (x)
;SELECT x FROM t3 WHERE x IN (1)
;SELECT x FROM t3 WHERE x IN (1.0)
;SELECT x FROM t3 WHERE x IN ('1')
;SELECT x FROM t3 WHERE x IN ('1.0')
;SELECT x FROM t3 WHERE 1 IN (x)
;SELECT x FROM t3 WHERE 1.0 IN (x)
;SELECT x FROM t3 WHERE '1' IN (x)
;SELECT x FROM t3 WHERE '1.0' IN (x)
;SELECT x FROM t4 WHERE x IN (1)
;SELECT x FROM t4 WHERE x IN (1.0)
;SELECT x FROM t4 WHERE x IN ('1')
;SELECT x FROM t4 WHERE x IN ('1.0')
;SELECT x FROM t4 WHERE x IN (1.11)
;SELECT x FROM t4 WHERE x IN ('1.11')
;SELECT x FROM t4 WHERE 1 IN (x)
;SELECT x FROM t4 WHERE 1.0 IN (x)
;SELECT x FROM t4 WHERE '1' IN (x)
;SELECT x FROM t4 WHERE '1.0' IN (x)
;SELECT x FROM t4 WHERE 1.11 IN (x)
;SELECT x FROM t4 WHERE '1.11' IN (x)
;SELECT x, y FROM t5 WHERE x IN (1)
;SELECT x, y FROM t5 WHERE x IN (1.0)
;SELECT x, y FROM t5 WHERE x IN ('1')
;SELECT x, y FROM t5 WHERE x IN ('1.0')
;SELECT x, y FROM t5 WHERE 1 IN (x)
;SELECT x, y FROM t5 WHERE 1.0 IN (x)
;SELECT x, y FROM t5 WHERE '1' IN (x)
;SELECT x, y FROM t5 WHERE '1.0' IN (x);