-- original: where5.test
-- credit:   http://www.sqlite.org/src/tree?ci=trunk&name=test

CREATE TABLE t1(x TEXT);
    CREATE TABLE t2(x INTEGER);
    CREATE TABLE t3(x INTEGER PRIMARY KEY);
    INSERT INTO t1 VALUES(-1);
    INSERT INTO t1 VALUES(0);
    INSERT INTO t1 VALUES(1);
    INSERT INTO t2 SELECT * FROM t1;
    INSERT INTO t3 SELECT * FROM t2
;SELECT * FROM t1 WHERE x<0
;SELECT * FROM t1 WHERE x<=0
;SELECT * FROM t1 WHERE x=0
;SELECT * FROM t1 WHERE x>=0
;SELECT * FROM t1 WHERE x>0
;SELECT * FROM t1 WHERE x<>0
;SELECT * FROM t1 WHERE x<NULL
;SELECT * FROM t1 WHERE x<=NULL
;SELECT * FROM t1 WHERE x=NULL
;SELECT * FROM t1 WHERE x>=NULL
;SELECT * FROM t1 WHERE x>NULL
;SELECT * FROM t1 WHERE x!=NULL
;SELECT * FROM t1 WHERE x IS NULL
;SELECT * FROM t1 WHERE x IS NOT NULL
;SELECT * FROM t2 WHERE x<0
;SELECT * FROM t2 WHERE x<=0
;SELECT * FROM t2 WHERE x=0
;SELECT * FROM t2 WHERE x>=0
;SELECT * FROM t2 WHERE x>0
;SELECT * FROM t2 WHERE x<>0
;SELECT * FROM t2 WHERE x<NULL
;SELECT * FROM t2 WHERE x<=NULL
;SELECT * FROM t2 WHERE x=NULL
;SELECT * FROM t2 WHERE x>=NULL
;SELECT * FROM t2 WHERE x>NULL
;SELECT * FROM t2 WHERE x!=NULL
;SELECT * FROM t2 WHERE x IS NULL
;SELECT * FROM t2 WHERE x IS NOT NULL
;SELECT * FROM t3 WHERE x<0
;SELECT * FROM t3 WHERE x<=0
;SELECT * FROM t3 WHERE x=0
;SELECT * FROM t3 WHERE x>=0
;SELECT * FROM t3 WHERE x>0
;SELECT * FROM t3 WHERE x<>0
;SELECT * FROM t3 WHERE x<NULL
;SELECT * FROM t3 WHERE x<=NULL
;SELECT * FROM t3 WHERE x=NULL
;SELECT * FROM t3 WHERE x>=NULL
;SELECT * FROM t3 WHERE x>NULL
;SELECT * FROM t3 WHERE x!=NULL
;SELECT * FROM t3 WHERE x IS NULL
;SELECT * FROM t3 WHERE x IS NOT NULL
;SELECT x<NULL FROM t3
;SELECT x<=NULL FROM t3
;SELECT x==NULL FROM t3
;SELECT x>NULL FROM t3
;SELECT x>=NULL FROM t3
;SELECT x!=NULL FROM t3
;SELECT x IS NULL FROM t3
;SELECT x IS NOT NULL FROM t3;